baseURL: "https://suspicious-mccarthy-febe6d.netlify.app/"
defaultContentLanguage: en
params:
  defaultLang: en
  mainSections: 
    - campaigns
    - posts
languages:
  en:
    contentDir: content/en
    title: QFTC
    weight: 1
    menu:
      main:
        - name: Home
          identifier: home
          url: /
          weight: 1
        - name: About Us
          identifier: about_us
          url: /about_us/
          weight: 2
        - name: Get Involved
          identifier: get_involved
          url: /get_involved/
          weight: 3
        - name: QFTC Archive
          identifier: archive
          url: /archive/
          weight: 4
        - name: Contact Us
          identifier: contact_us
          url: /contact_us/
          weight: 5
    params:
      languageName: English
      campaigns_cta: Take Action
      posts_cta: Read More
  zh:
    contentDir: content/zh
    languagedirection: rtl
    title: QFTC
    weight: 2
    menu:
      main:
        - name: Home
          identifier: home
          url: /
          weight: 1
        - name: About Us
          identifier: about_us
          url: /about_us/
          weight: 2
        - name: Get Involved
          identifier: get_involved
          url: /get_involved/
          weight: 3
        - name: QFTC Archive
          identifier: archive
          url: /archive/
          weight: 4
        - name: Contact Us
          identifier: contact_us
          url: /contact_us/
          weight: 5
    params:
      languageName: 中国人
      campaigns_cta: Take Action
      posts_cta: Read More
