baseURL: "https://zen-mirzakhani-bf3dbc.netlify.app/"
defaultContentLanguage: en
params:
  mainSections: 
    - actions
    - posts
languages:
  zh:
    languagedirection: rtl
    title: Chinese versions
    weight: 2
  en:
    title: English Version
    weight: 1
