---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
- type: heading
  label: English Content
- type: directory
  path: content/en/posts
  label: English Posts
  create: documents
  match: "**/*"
  templates:
  - post-template
- type: directory
  path: content/en/campaigns
  label: English Campaigns
  create: documents
  match: "**/*"
  templates:
  - action-template
- type: heading
  label: Chinese content
- type: directory
  path: content/zh/posts
  label: Chinese Posts
  create: documents
  match: "**/*"
  templates:
  - post-template
- type: directory
  path: content/zh/campaigns
  label: Chinese Campaigns
  create: documents
  match: "**/*"
  templates:
  - action-template
- type: heading
  label: Resources
- type: document
  path: data/task_forces.yml
  label: Task Forces
- type: document
  path: data/other_groups.yml
  label: Other local groups
upload_dir: content/uploads/images
public_path: "/uploads/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
